In [1]:
import tensorflow as tf
import keras


In [2]:
train = keras.utils.image_dataset_from_directory("./data/train/",image_size=(500,500))

Found 1034 files belonging to 3 classes.


In [3]:
test = keras.utils.image_dataset_from_directory("./data/test/",image_size=(500,500))

Found 128 files belonging to 3 classes.


In [4]:
val = keras.utils.image_dataset_from_directory("./data/validation/",image_size=(500,500))

Found 133 files belonging to 3 classes.


In [5]:
for image, label in train:
    print(f'{image.shape}')
    print(f'{label.shape}')
    print(label)

(32, 500, 500, 3)
(32,)
tf.Tensor([0 2 1 0 2 0 0 1 1 2 2 0 0 0 1 2 2 1 2 0 2 1 2 0 0 2 1 1 1 1 2 1], shape=(32,), dtype=int32)
(32, 500, 500, 3)
(32,)
tf.Tensor([2 0 2 2 1 0 2 2 2 1 1 2 0 1 0 1 2 1 2 0 0 2 1 1 1 0 2 0 0 1 1 2], shape=(32,), dtype=int32)
(32, 500, 500, 3)
(32,)
tf.Tensor([2 0 1 1 1 0 1 1 2 1 1 2 2 2 0 2 2 2 2 2 2 0 1 1 0 0 2 2 1 2 1 0], shape=(32,), dtype=int32)
(32, 500, 500, 3)
(32,)
tf.Tensor([0 2 0 0 0 1 1 0 1 2 2 2 0 1 0 1 0 1 2 2 0 2 2 1 2 1 0 2 0 2 1 0], shape=(32,), dtype=int32)
(32, 500, 500, 3)
(32,)
tf.Tensor([2 0 2 1 1 2 2 0 1 0 0 1 1 2 0 2 0 0 0 2 0 0 2 1 0 2 0 2 2 2 1 2], shape=(32,), dtype=int32)
(32, 500, 500, 3)
(32,)
tf.Tensor([0 2 2 1 1 2 2 2 0 2 1 2 1 2 0 0 0 0 0 1 1 2 0 2 1 2 2 1 0 0 0 0], shape=(32,), dtype=int32)
(32, 500, 500, 3)
(32,)
tf.Tensor([2 0 1 0 0 2 0 0 0 0 2 2 2 0 0 0 0 1 2 0 2 1 0 1 0 2 0 0 1 0 1 0], shape=(32,), dtype=int32)
(32, 500, 500, 3)
(32,)
tf.Tensor([0 0 2 1 2 1 2 1 2 1 1 1 0 1 0 1 0 2 0 0 0 1 1 0 2 2 0 2 1 1 0 0], shape=(32,

In [6]:
from keras import layers,regularizers
from keras.callbacks import ReduceLROnPlateau, EarlyStopping

In [7]:
classes = train.class_names
rlr = ReduceLROnPlateau(patience=3),
es = EarlyStopping(monitor="val_accuracy", patience=5,restore_best_weights=True)

In [8]:
model = keras.Sequential([
    layers.Rescaling(1./255, input_shape=(500,500,3)),
    layers.RandomFlip("horizontal_and_vertical"),
    layers.RandomRotation(0.2),
    layers.Conv2D(16,(3,3),activation="relu",kernel_regularizer=regularizers.l1_l2()),
    layers.MaxPool2D(),
    layers.Conv2D(32,(3,3),activation="relu",kernel_regularizer=regularizers.l1_l2()),
    layers.MaxPool2D(),
    layers.Conv2D(64,(3,3),activation="relu",kernel_regularizer=regularizers.l1_l2()),
    layers.MaxPool2D(),
    layers.Flatten(),
    layers.Dense(128,activation="relu"),
    layers.Dense(len(classes))
    
])

In [9]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 rescaling (Rescaling)       (None, 500, 500, 3)       0         
                                                                 
 conv2d (Conv2D)             (None, 498, 498, 16)      448       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 249, 249, 16)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 247, 247, 32)      4640      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 123, 123, 32)     0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 121, 121, 64)      1

In [11]:
history = model.fit(
  train,
  validation_data=val,
  epochs=10,
  callbacks=[rlr,es]
)

Epoch 1/10
33/33 [==============================] - 73s 2s/step - loss: 10.4403 - accuracy: 0.4420 - val_loss: 7.4452 - val_accuracy: 0.6015 - lr: 0.0010
Epoch 2/10
33/33 [==============================] - 72s 2s/step - loss: 5.9081 - accuracy: 0.6518 - val_loss: 4.5506 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 3/10
33/33 [==============================] - 72s 2s/step - loss: 3.9490 - accuracy: 0.6954 - val_loss: 3.4204 - val_accuracy: 0.7068 - lr: 0.0010
Epoch 4/10
33/33 [==============================] - 73s 2s/step - loss: 3.1044 - accuracy: 0.7476 - val_loss: 2.8563 - val_accuracy: 0.7444 - lr: 0.0010
Epoch 5/10
33/33 [==============================] - 74s 2s/step - loss: 2.6782 - accuracy: 0.7727 - val_loss: 2.6105 - val_accuracy: 0.7218 - lr: 0.0010
Epoch 6/10
33/33 [==============================] - 74s 2s/step - loss: 2.3706 - accuracy: 0.8172 - val_loss: 2.2990 - val_accuracy: 0.7594 - lr: 0.0010
Epoch 7/10
33/33 [==============================] - 74s 2s/step - loss: 2.1110 - 

In [12]:
model.evaluate(test)

4/4 [==============================] - 3s 544ms/step - loss: 1.6515 - accuracy: 0.7422


[1.6514843702316284, 0.7421875]

In [ ]:
model.save("beans_classifier.keras")